nuxeo/nuxeo-admin-console-ui

PROJECT_STRUCTURE.md
angular.json
package-lock.json
package.json
src
tsconfig.app.json
tsconfig.json
tsconfig.spec.json

Project boilerplate and configurations added

Project boilerplate and configurations added

---

src/app/app.module.ts
src/app/layouts/admin-menu/admin-menu.component.html
src/app/layouts/admin-menu/admin-menu.component.scss
src/app/layouts/admin-menu/admin-menu.component.ts
src/app/layouts/admin-menu/admin-menu.constants.ts
src/styles.scss

https://jira.nuxeo.com/browse/NXP-32255

NXP-32255: Add side navigation bar

---

src/app/admin-app.component.html
src/app/admin-app.component.ts
src/app/app.module.ts
src/app/features/admin-warning/admin-warning.component.html
src/app/features/admin-warning/admin-warning.component.scss
src/app/features/admin-warning/admin-warning.component.ts
src/app/shared/components/admin-warning/admin-warning.component.ts
src/app/shared/services/admin-common.service.ts

https://jira.nuxeo.com/browse/NXP-32250

NXP-32250: Admin console - Warning on launch

---

src/app/layouts/admin-header/admin-header.component.scss

https://jira.nuxeo.com/browse/NXP-32574

NXP-32574- update profile icon style on hover

---

src/app/app-routing.module.ts
src/app/features/admin-bulk-action-monitoring/admin-bulk-action-monitoring-routing.module.ts
src/app/features/admin-bulk-action-monitoring/admin-bulk-action-monitoring.module.ts
src/app/features/admin-elastic-search-reindex/admin-elastic-search-reindex-routing.module.ts
src/app/features/admin-elastic-search-reindex/admin-elastic-search-reindex.module.ts
src/app/features/admin-full-text-reindex/admin-full-text-reindex-routing.module.ts
src/app/features/admin-full-text-reindex/admin-full-text-reindex.module.ts
src/app/features/admin-home/admin-home-routing.module.ts
src/app/features/admin-home/admin-home.module.ts
src/app/features/admin-picture-render-generation/admin-picture-render-generation-routing.module.ts
src/app/features/admin-picture-render-generation/admin-picture-render-generation.module.ts
src/app/features/admin-system-information/admin-system-information-routing.modules.ts
src/app/features/admin-system-information/admin-system-information.module.ts
src/app/features/admin-thumbnail-generation/admin-thumbnail-generation-routing.module.ts
src/app/features/admin-thumbnail-generation/admin-thumbnail-generation.module.ts
src/app/features/admin-video-render-generation/admin-video-render-generation-routing.module.ts
src/app/features/admin-video-render-generation/admin-video-render-generation.module.ts
src/app/layouts/admin-menu/admin-menu.component.html
src/app/layouts/admin-menu/admin-menu.constants.ts
src/index.html

https://jira.nuxeo.com/browse/NXP-32522
Lazy-loading feature modules
https://angular.io/guide/lazy-loading-ngmodules

NXP-32522: main menu  route creation  & component linking

---

angular.json
src/app/auth/services/auth-interceptor.service.ts
src/proxy.conf.json

https://jira.nuxeo.com/browse/NXP-32650

NXP-32650: added proxy configuration & basic authorization to access management api endpoints

---

.github/workflows/lint.yaml
.github/workflows/main.yaml
.github/workflows/utest.yaml
nuxeo-admin-console-web/src/main/resources/OSGI-INF/deployment-fragment.xml

This is needed as the routing is done client-side through the
Angular app

NXP-32705: add a Tomcat RewriteRule for the Nuxeo Admin Angular app and add main workflow 

---

nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/folder-es-reindex/folder-es-reindex.component.html
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/folder-es-reindex/folder-es-reindex.component.scss
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/folder-es-reindex/folder-es-reindex.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/nxql-es-reindex/nxql-es-reindex.component.html
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/nxql-es-reindex/nxql-es-reindex.component.scss
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/nxql-es-reindex/nxql-es-reindex.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/elastic-search-reindex.module.ts
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/services/elastic-search-reindex.service.ts

https://jira.nuxeo.com/browse/NXP-32275

NXP-32275: admin-console-confirmation-request-dialog

---

nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/document-es-reindex/document-es-reindex.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/folder-es-reindex/folder-es-reindex.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/nxql-es-reindex/nxql-es-reindex.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/home/components/probes-summary/probes-summary.component.scss
nuxeo-admin-console-web/angular-app/src/app/features/home/services/home.service.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/home/services/home.service.ts
nuxeo-admin-console-web/angular-app/src/app/features/home/store/effects.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/home/store/effects.ts
nuxeo-admin-console-web/angular-app/src/app/shared/types/capabilities.interface.ts
nuxeo-admin-console-web/angular-app/src/assets/version-info.json

https://jira.nuxeo.com/browse/NXP-32700

NXP 32700: home page UI changes refactoring and api integration

---

nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/elastic-search-reindex-modal/elastic-search-reindex-modal.component.html
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/services/elastic-search-reindex.service.ts
nuxeo-admin-console-web/angular-app/src/app/layouts/header-bar/header-bar.component.scss

https://jira.nuxeo.com/browse/NXP-32700

NXP-32700: home page and elastic search ui refactoring

---

nuxeo-admin-console-web/angular-app/src/app/layouts/menu-bar/menu-bar.component.scss

https://jira.nuxeo.com/browse/NXP-32700

NXP-32700: sidenav focus fix

---

.gitignore
nuxeo-admin-console-web/angular-app/src/app/app.component.html
nuxeo-admin-console-web/angular-app/src/app/app.component.scss
nuxeo-admin-console-web/angular-app/src/app/app.component.ts
nuxeo-admin-console-web/angular-app/src/app/app.constants.ts
nuxeo-admin-console-web/angular-app/src/app/auth/services/auth.service.ts
nuxeo-admin-console-web/angular-app/src/app/auth/types/authResponse.interface.ts
nuxeo-admin-console-web/angular-app/src/app/layouts/header-bar/header-bar.component.html
nuxeo-admin-console-web/angular-app/src/app/layouts/header-bar/header-bar.component.ts
nuxeo-admin-console-web/angular-app/src/app/layouts/menu-bar/menu-bar.component.scss
nuxeo-admin-console-web/angular-app/src/app/shared/types/user.interface.ts

https://jira.nuxeo.com/browse/NXP-32755
Hyland Icon ref: https://zeroheight.com/5932dab8d/v/41976/p/0716ad-icon
Update logout Icon:
Error Message View:

Task nxp 32755 error message for non privileged users

---

nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/services/elastic-search-reindex.service.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/services/elastic-search-reindex.service.ts
nuxeo-admin-console-web/angular-app/src/app/features/home/services/home.service.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/home/services/home.service.ts
nuxeo-admin-console-web/angular-app/src/app/layouts/header-bar/header-bar.component.html
nuxeo-admin-console-web/angular-app/src/app/layouts/header-bar/header-bar.component.ts
nuxeo-admin-console-web/angular-app/src/app/layouts/header-bar/header-bar.constants.ts
nuxeo-admin-console-web/angular-app/src/app/shared/services/nuxeo-js-client.service.ts

2nd PR
https://jira.nuxeo.com/browse/NXP-32755

NXP-32772: handle urls

---

.github/workflows/veracode.yaml

https://jira.nuxeo.com/browse/NXP-32731

NXP-32731: add veracode workflow

---

nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/elastic-search-reindex-modal/elastic-search-reindex-modal.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/elastic-search-reindex-modal/elastic-search-reindex-modal.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/nxql-es-reindex/nxql-es-reindex.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/nxql-es-reindex/nxql-es-reindex.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/elastic-search-reindex.constants.ts
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/elastic-search-reindex.interface.ts
nuxeo-admin-console-web/angular-app/src/app/features/home/services/home.service.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/home/services/home.service.ts

https://jira.nuxeo.com/browse/NXP-32772

Bug NXP 32772 fix incorrect message nxql query zero documents

---

nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/document-es-reindex/document-es-reindex.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/document-es-reindex/document-es-reindex.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/elastic-search-reindex-modal/elastic-search-reindex-modal.component.html
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/elastic-search-reindex-modal/elastic-search-reindex-modal.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/elastic-search-reindex-modal/elastic-search-reindex-modal.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/folder-es-reindex/folder-es-reindex.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/folder-es-reindex/folder-es-reindex.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/nxql-es-reindex/nxql-es-reindex.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/nxql-es-reindex/nxql-es-reindex.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/elastic-search-reindex.constants.ts
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/elastic-search-reindex.interface.ts
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/services/elastic-search-reindex.service.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/services/elastic-search-reindex.service.ts

https://jira.nuxeo.com/browse/NXP-32771

Bugfix-NXP-32271: system unresponsive for special chars input

---

nuxeo-admin-console-web/angular-app/src/app/features/home/components/probes-summary/probes-summary.component.html
nuxeo-admin-console-web/angular-app/src/app/features/home/components/probes-summary/probes-summary.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/home/components/probes-summary/probes-summary.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/home/home.constants.ts

https://jira.nuxeo.com/browse/NXP-32254

NXP-32254 : probes summary changes

---

nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/nxql-es-reindex/nxql-es-reindex.component.html
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/nxql-es-reindex/nxql-es-reindex.component.scss
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/elastic-search-reindex.constants.ts

https://jira.nuxeo.com/browse/NXP-32769

admin console miscellaneous fix

---

nuxeo-admin-console-web/angular-app/src/app/app.component.ts
nuxeo-admin-console-web/angular-app/src/app/auth/store/effects.ts
nuxeo-admin-console-web/angular-app/src/app/layouts/header-bar/header-bar.component.ts

https://jira.nuxeo.com/browse/NXP-32791

NXP-32791: logout and username display firefox

---

nuxeo-admin-console-web/angular-app/src/app/app.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/warning/warning.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/layouts/base-layout/base-layout.module.ts
nuxeo-admin-console-web/angular-app/src/app/layouts/header-bar/header-bar.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/layouts/header-bar/header-bar.module.ts
nuxeo-admin-console-web/angular-app/src/app/layouts/menu-bar/menu-bar.module.ts

https://jira.nuxeo.com/browse/NXP-32730

NXP-32730: add unit test for logout & username

---

nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/document-es-reindex/document-es-reindex.component.html
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/document-es-reindex/document-es-reindex.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/folder-es-reindex/folder-es-reindex.component.html
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/folder-es-reindex/folder-es-reindex.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/nxql-es-reindex/nxql-es-reindex.component.html
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/nxql-es-reindex/nxql-es-reindex.component.ts

https://jira.nuxeo.com/browse/NXP-32799

 NXP-32799: user is allowed to call reindex action multiple times even when the dialog box is already opened

---

.github/workflows/main.yaml
.github/workflows/promote.yaml
nuxeo-admin-console-package/pom.xml

https://github.com/nuxeo/nuxeo-admin-console-ui/pull/93

NXP-32713: rename nuxeo package name

---

nuxeo-admin-console-web/angular-app/angular.json

https://github.com/nuxeo/nuxeo-admin-console-ui/pull/131

NXP-32713: increment budget size to 5mb

---

nuxeo-admin-console-web/angular-app/src/app/shared/services/network.service.ts

https://jira.nuxeo.com/browse/NAC-255

NAC-255: logout is not working for Admin Console

---

nuxeo-admin-console-web/angular-app/src/app/features/bulk-action-monitoring/components/bulk-action-monitoring/bulk-action-monitoring-form/bulk-action-monitoring-form.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/bulk-action-monitoring/components/bulk-action-monitoring/bulk-action-monitoring.component.ts

https://jira.nuxeo.com/browse/NAC-138

NAC-138: Admin console - Bulk action monitoring details

---

nuxeo-admin-console-web/angular-app/src/app/features/bulk-action-monitoring/components/bulk-action-monitoring/bulk-action-monitoring-result/bulk-action-monitoring-summary/bulk-action-monitoring-summary.component.scss
nuxeo-admin-console-web/angular-app/src/app/features/bulk-action-monitoring/components/bulk-action-monitoring/bulk-action-monitoring-result/bulk-action-monitoring-summary/bulk-action-monitoring-summary.component.ts

https://jira.nuxeo.com/browse/NAC-138

NAC-138: error text modification

---

.github/workflows/code-freeze.yaml

NAC-247: codefreeze.yaml (#156)

---

nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/nxql-es-reindex/nxql-es-reindex.component.html
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/nxql-es-reindex/nxql-es-reindex.component.scss
nuxeo-admin-console-web/angular-app/src/app/features/home/components/registration-version/registration-version.component.scss
nuxeo-admin-console-web/angular-app/src/app/layouts/base-layout/components/base-layout.component.scss

https://jira.nuxeo.com/browse/NAC-257

NAC-257: accessibility issues after removing extra css layers

---

.github/workflows/hotfix-checker.yaml

Reverts nuxeo/nuxeo-admin-console-ui#163

Revert "fix hotfix-checker.yaml"

---

.github/workflows/hotfix-checker.yaml

It includes updates in preparation for the upcoming release.
**Release Candidate:** [v23.0.3-rc.15](https://github.com/nuxeo/nuxeo-admin-console-ui/releases/tag/v23.0.3-rc.15).
**Create Beta Release:** [v23.0.3-beta.0](https://github.com/nuxeo/nuxeo-admin-console-ui/releases/tag/v23.0.3-beta.0).

Code Freeze: Merge dev into main with Release Candidate v23.0.3-rc.15

---

.github/workflows/hotfix-checker.yaml

It includes updates in preparation for the upcoming release.
**Release Candidate:** [v23.0.3-rc.14](https://github.com/nuxeo/nuxeo-admin-console-ui/releases/tag/v23.0.3-rc.14).
**Create Beta Release:** [v23.0.3-beta.0](https://github.com/nuxeo/nuxeo-admin-console-ui/releases/tag/v23.0.3-beta.0).

Code Freeze: Merge dev into main with Release Candidate v23.0.3-rc.14

---

nuxeo-admin-console-web/angular-app/src/app/features/home/components/probes-summary/probes-summary.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/probes/probes.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/probes-data/components/probes-data.component.html
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/probes-data/components/probes-data.component.scss
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/probes-data/components/probes-data.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/probes-data/components/probes-data.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/probes-data/probes-data.constants.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/probes-data/probes-data.module.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/probes-data/services/probes-data.service.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/probes-data/services/probes-data.service.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/probes-data/store/actions.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/probes-data/store/actions.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/probes-data/store/effects.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/probes-data/store/effects.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/probes-data/store/reducers.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/probes-data/store/reducers.ts
nuxeo-admin-console-web/angular-app/src/app/shared/constants/rest-end-ponts.constants.ts
nuxeo-admin-console-web/angular-app/src/app/shared/services/common.service.spec.ts
nuxeo-admin-console-web/angular-app/src/app/shared/services/common.service.ts

https://jira.nuxeo.com/browse/NAC-128

NAC-128: probe status update

---

nuxeo-admin-console-web/angular-app/src/app/features/probes/probes.component.html
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/probes-data/components/probes-data.component.html
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/probes-data/probes-data.constants.ts

https://jira.nuxeo.com/browse/NAC-277

NAC-277: Probes title & font fixed

---

nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/folder-es-reindex/folder-es-reindex.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/nxql-es-reindex/nxql-es-reindex.component.html
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/nxql-es-reindex/nxql-es-reindex.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/elastic-search-reindex.constants.ts

https://jira.nuxeo.com/browse/NAC-275

NAC 275 reindex modify query for folder count

---

nuxeo-admin-console-web/angular-app/src/app/features/home/components/probes-summary/probes-summary.component.scss

Reverts nuxeo/nuxeo-admin-console-ui#186

Revert "NAC-286: Additional information not loading issue fix"

---

nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/folder-es-reindex/folder-es-reindex.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/nxql-es-reindex/nxql-es-reindex.component.html
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/nxql-es-reindex/nxql-es-reindex.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/elastic-search-reindex.constants.ts

https://jira.nuxeo.com/browse/NAC-284

NAC-284: fixed payload query for reindex not working

---

nuxeo-admin-console-web/angular-app/src/app/app-routing.module.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/generic-multi-feature-layout.mapping.ts
nuxeo-admin-console-web/angular-app/src/app/features/thumbnail-generation/thumbnail-generation.constants.ts
nuxeo-admin-console-web/angular-app/src/app/layouts/menu-bar/menu-bar.constants.ts
nuxeo-admin-console-web/angular-app/src/app/shared/constants/rest-end-ponts.constants.ts

https://jira.nuxeo.com/browse/NAC-134

NAC-134: single document thumbnal generation

---

nuxeo-admin-console-web/angular-app/src/app/features/bulk-action-monitoring/components/bulk-action-monitoring/bulk-action-monitoring-result/bulk-action-monitoring-summary/bulk-action-monitoring-summary.component.html
nuxeo-admin-console-web/angular-app/src/app/features/bulk-action-monitoring/components/bulk-action-monitoring/bulk-action-monitoring-result/bulk-action-monitoring-summary/bulk-action-monitoring-summary.component.scss
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/generic-multi-feature-layout.mapping.ts
nuxeo-admin-console-web/angular-app/src/app/features/thumbnail-generation/thumbnail-generation.constants.ts

https://jira.nuxeo.com/browse/NAC-132
https://jira.nuxeo.com/browse/NAC-134

NAC-132: nxql query thumbnail generation

---

nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/document-tab/document-tab.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/folder-tab/folder-tab.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/nxql-tab/nxql-tab.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/generic-multi-feature-layout.mapping.ts
nuxeo-admin-console-web/angular-app/src/app/features/thumbnail-generation/thumbnail-generation.constants.ts

https://jira.nuxeo.com/browse/NAC-142

NAC-142: folder thumbnail generation and unit tests

---

nuxeo-admin-console-web/angular-app/src/app/app-routing.module.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/document-tab/document-tab.component.html
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/document-tab/document-tab.component.scss
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/document-tab/document-tab.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/folder-tab/folder-tab.component.html
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/folder-tab/folder-tab.component.scss
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/folder-tab/folder-tab.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/nxql-tab/nxql-tab.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/generic-multi-feature-layout.interface.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/generic-multi-feature-layout.mapping.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/services/generic-multi-feature-endpoints.service.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/services/generic-multi-feature-endpoints.service.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/services/generic-multi-feature-utilities.service.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/services/generic-multi-feature-utilities.service.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/store/actions.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/store/actions.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/store/effects.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/store/effects.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/store/reducers.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/video-renditions-generation/video-renditions-generation.constants.ts
nuxeo-admin-console-web/angular-app/src/app/layouts/menu-bar/menu-bar.constants.ts
nuxeo-admin-console-web/angular-app/src/app/shared/constants/rest-end-ponts.constants.ts
nuxeo-admin-console-web/angular-app/src/app/shared/services/network.service.spec.ts
nuxeo-admin-console-web/angular-app/src/app/shared/services/network.service.ts

https://jira.nuxeo.com/browse/NAC-140
https://jira.nuxeo.com/browse/NAC-144
https://jira.nuxeo.com/browse/NAC-133

NAC-140 Admin console single video renditions

---

nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/store/effects.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/store/effects.ts

https://jira.nuxeo.com/browse/NAC-144

NAC-144: folder video renditions - handled error scenario for conversion names

---

nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/nxql-tab/nxql-tab.component.html
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/nxql-tab/nxql-tab.component.scss
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/nxql-tab/nxql-tab.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/nxql-tab/nxql-tab.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/generic-multi-feature-layout.mapping.ts

https://jira.nuxeo.com/browse/NAC-305

NAC-305: Add conversion names & information to recompute fields for NXQL query

---

nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/elastic-search-reindex.constants.ts
nuxeo-admin-console-web/angular-app/src/app/features/pictures/pictures-renditions.constants.ts
nuxeo-admin-console-web/angular-app/src/app/features/thumbnail-generation/thumbnail-generation.constants.ts
nuxeo-admin-console-web/angular-app/src/app/features/video-renditions-generation/video-renditions-generation.constants.ts

https://jira.nuxeo.com/browse/NAC-305

NAC-305: Optimized queries

---

nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/generic-modal/generic-modal.component.html
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/nxql-tab/nxql-tab.component.html
nuxeo-admin-console-web/angular-app/src/styles.scss

https://hyland.atlassian.net/browse/NAC-319

NAC-319: fixed incorrect abort button color and font of dropdown

---

nuxeo-admin-console-web/angular-app/src/app/features/bulk-action-monitoring/components/bulk-action-monitoring/bulk-action-monitoring-result/bulk-action-monitoring-details/bulk-action-monitoring-details.component.scss
nuxeo-admin-console-web/angular-app/src/app/features/bulk-action-monitoring/components/bulk-action-monitoring/bulk-action-monitoring-result/bulk-action-monitoring-summary/bulk-action-monitoring-summary.component.html
nuxeo-admin-console-web/angular-app/src/app/features/bulk-action-monitoring/components/bulk-action-monitoring/bulk-action-monitoring-result/bulk-action-monitoring-summary/bulk-action-monitoring-summary.component.scss
nuxeo-admin-console-web/angular-app/src/app/features/bulk-action-monitoring/components/bulk-action-monitoring/bulk-action-monitoring-result/bulk-action-monitoring-summary/bulk-action-monitoring-summary.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/document-tab/document-tab.component.scss
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/document-tab/document-tab.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/document-tab/document-tab.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/folder-tab/folder-tab.component.scss
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/folder-tab/folder-tab.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/folder-tab/folder-tab.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/generic-modal/generic-modal.component.html
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/nxql-tab/nxql-tab.component.html
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/nxql-tab/nxql-tab.component.scss
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/nxql-tab/nxql-tab.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/nxql-tab/nxql-tab.component.ts
nuxeo-admin-console-web/angular-app/src/styles.scss

https://hyland.atlassian.net/browse/NAC-320

NAC-320 dialog focus & input text color

---

nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/generic-multi-feature-layout.constants.ts

https://hyland.atlassian.net/browse/NAC-136

NAC-136: Admin Console folder tab fulltext reindex

---

nuxeo-admin-console-web/angular-app/src/index.jsp

https://hyland.atlassian.net/browse/NAC-335

NAC-335: admin console with strict csp changes fixed

---

nuxeo-admin-console-web/angular-app/src/app/features/stream/components/stream-form/stream-form.component.html
nuxeo-admin-console-web/angular-app/src/app/features/stream/components/stream-form/stream-form.component.scss
nuxeo-admin-console-web/angular-app/src/app/features/stream/components/stream-form/stream-form.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/stream/components/stream-form/stream-form.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/stream/components/stream-records-status/stream-records-status.component.html
nuxeo-admin-console-web/angular-app/src/app/features/stream/components/stream-records-status/stream-records-status.component.scss
nuxeo-admin-console-web/angular-app/src/app/features/stream/components/stream-records-status/stream-records-status.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/stream/components/stream-records-status/stream-records-status.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/stream/components/stream-records/stream-records.component.html
nuxeo-admin-console-web/angular-app/src/app/features/stream/components/stream-records/stream-records.component.scss
nuxeo-admin-console-web/angular-app/src/app/features/stream/components/stream-records/stream-records.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/stream/components/stream.component.html
nuxeo-admin-console-web/angular-app/src/app/features/stream/components/stream.component.scss
nuxeo-admin-console-web/angular-app/src/app/features/stream/components/stream.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/stream/components/stream.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/stream/services/stream.service.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/stream/services/stream.service.ts
nuxeo-admin-console-web/angular-app/src/app/features/stream/store/actions.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/stream/store/actions.ts
nuxeo-admin-console-web/angular-app/src/app/features/stream/store/effects.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/stream/store/effects.ts
nuxeo-admin-console-web/angular-app/src/app/features/stream/store/reducers.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/stream/store/reducers.ts
nuxeo-admin-console-web/angular-app/src/app/features/stream/stream.constants.ts
nuxeo-admin-console-web/angular-app/src/app/features/stream/stream.interface.ts
nuxeo-admin-console-web/angular-app/src/styles.scss

https://hyland.atlassian.net/browse/NAC-349

NAC-349: add position options rewind limit timeout config

---

nuxeo-admin-console-web/angular-app/src/app/app.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/app.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/bulk-action-monitoring/components/bulk-action-monitoring/bulk-action-monitoring-form/bulk-action-monitoring-form.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/bulk-action-monitoring/components/bulk-action-monitoring/bulk-action-monitoring-form/bulk-action-monitoring-form.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/home/components/registration-version/registration-version.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/home/components/registration-version/registration-version.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/stream/components/stream-form/stream-form.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/stream/components/stream-form/stream-form.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/stream/components/stream.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/stream/components/stream.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/document-tab/document-tab.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/document-tab/document-tab.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/error-modal/error-modal.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/folder-tab/folder-tab.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/folder-tab/folder-tab.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/nxql-tab/nxql-tab.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/nxql-tab/nxql-tab.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/generic-multi-feature-layout.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/generic-multi-feature-layout.mapping.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/probes-data/components/probes-data.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/probes-data/components/probes-data.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/warning/warning.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/warning/warning.component.ts
nuxeo-admin-console-web/angular-app/src/app/layouts/header-bar/header-bar.component.ts
nuxeo-admin-console-web/angular-app/src/app/shared/services/persistence.service.spec.ts

NAC-3733-Replace manual unsubscriptions with takeUntil operator

NAC-373-Replace manual unsubscriptions with takeUntil operator

---

nuxeo-admin-console-web/angular-app/src/app/features/home/components/probes-summary/probes-summary.component.scss
nuxeo-admin-console-web/angular-app/src/app/features/home/components/probes-summary/probes-summary.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/probes/probes.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/stream/store/effects.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/document-tab/document-tab.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/folder-tab/folder-tab.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/components/nxql-tab/nxql-tab.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/generic-multi-feature-layout/services/generic-multi-feature-utilities.service.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/probes-data/components/probes-data.component.html
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/probes-data/components/probes-data.component.scss
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/probes-data/components/probes-data.component.spec.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/probes-data/components/probes-data.component.ts
nuxeo-admin-console-web/angular-app/src/app/features/sub-features/probes-data/probes-data.module.ts

Feat nac 374 implement pagination on probes table

Feat nac 374 implement pagination on probes table
